openapi: 3.0.0
info:
  title: Заказ ресурса на облаке
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод get list ресурсов в облако
      tags:
        - Clouds
      operationId: getAllClouds
      responses:
        "200":
          description: Успешный ответ со списком ресурсов в облоко
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Все остальное если не найдется (default)
          content:
            adplication/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Создание заказа на облоко
      tags:
        - Clouds
      operationId: CreateCloud
      requestBody: 
        content:
          adplication/json:
            schema:
              $ref: "#/components/schemas/Error"
      responses:
        "200":
           description: Заказ размещен (Исправлен)
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Clouds"
        "default":
           description: Все остальное
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
  /clouds/{cloud_id}:
    get:
      summary: Метод получения заказа на облоко по id
      tags:
        - Clouds
      operationId: getCloudById
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        "200":
           description: Успекшный ответ заказом облока по ID
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Cloud"
        "404":
           description: Заказ с ID не найден 
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
        "default":
           description: Все остальное
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления заказа на облоко по ID
      tags:
        - Clouds
      operationId: removeCloudByID
      parameters:
        - name: cloud_id
          in: path
          required: true
          description: Идентификатор заказа облака
          schema:
            type: string
          example: f102b615
      responses:
        "204":
          description: Заказ удален
        "404":
          description: Заказ с ID не был найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
          "default":
           description: Все остальное
           content:
             adplication/json:
               schema:
                 $ref: "#/components/schemas/Error" 
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - HDD
      properties:
        cloud_id:
          type: string
          example: f102b615
        id_client:
          type: string
          example: f102b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: ОС сервера
        RAM:
          type: string
          example: 128
          description: Объем Оператив памяти
        CPU:
          type: string
          example: 8
          description: Кол-во ядер процессора
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string